#!/usr/bin/env bash

# I do not use bash directly.
# So this file only includes `brew` binaries.

# global:
PATH="/usr/local/bin:/usr/bin:/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$HOME/.poetry/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi
