#!/usr/bin/env bash

# I do not use bash directly.
# So this file only includes `brew` binaries.

# global:
PATH="/usr/local/bin:/usr/bin:/bin:$PATH"

export PATH="$(pyenv root)/shims:$HOME/.poetry/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
