#!/usr/bin/env bash
# Settings for `nano` editor
# Full list of settings might be shown via `man nano`
# or here: https://www.nano-editor.org/dist/v3/nanorc.5.html

# Editor:
set morespace

set tabstospaces
set trimblanks

set softwrap
set atblanks
set constantshow

# UX:
set smooth

# Extra files:
set backup
set backupdir "~/backups"
set historylog

# line numbers are copied with text,
# it is not useful:
# set linenumbers
