---
.common-list: &common-list
  - d_pyenv
  - f_gitconfig
  - f_ssh_config
  - d_shell
  - f_zshrc
  - f_hushlogin
  - f_antigenrc
  - d_mc
  - f_gitignore_global
  - f_editorconfig
  - f_nanorc
  - f_bash_profile
  - f_bashrc
actions:
  post:
    pip_upgrade: python3 -m pip install --upgrade pip --user
    pipx_install: python3 -m pip install -U pipx
    pipx_install_packages: while read in; do pipx install "$in"; done < dotfiles/requirements.txt
    fzf_install: ~/.fzf/install
    pyenv_install_python: pyenv install {{@@ python_version @@}}
    pyenv_set_global_python: pyenv global {{@@ python_version @@}}
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: link
  link_on_import: link
variables:
  python_version: "3.8.6"
dotfiles:
  d_pyenv:
    src: ../pyenv
    dst: ~/.pyenv
  d_fzf:
    src: ../fzf
    dst: ~/.fzf
    actions:
      - fzf_install
  d_antigen:
    src: ../antigen
    dst: ~/antigen
  f_antigen.zsh:
    src: ../antigen/antigen.zsh
    dst: ~/.antigen.zsh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  d_shell:
    src: shell
    dst: ~/.shell
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_hushlogin:
    src: hushlogin
    dst: ~/.hushlogin
  f_antigenrc:
    src: antigenrc
    dst: ~/.antigenrc
  d_mc:
    src: config/mc
    dst: ~/.config/mc
    link: link_children
  f_gitignore_global:
    src: gitignore_global
    dst: ~/.gitignore_global
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  f_nanorc:
    src: nanorc
    dst: ~/.nanorc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_python:
    src:
    dst:
    actions:
      - pip_upgrade
      - pyenv_install_python
      - pyenv_set_global_python
      - pipx_install
      - pipx_install_packages
profiles:
  mac_os:
    dotfiles:
      *common-list
  linux:
    dotfiles:
      *common-list
  python:
    dotfiles:
      - f_python
