#!/usr/bin/env bash
# export PATH="/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export ZSH="$HOME/.oh-my-zsh"
# That way Antigen will store it's info in an independent file, so it won't get corrupted by any other script/software
export ADOTDIR="${HOME}/.antigen"
export ANTIGEN_COMPDUMP="${ADOTDIR}/.zcompdump"
export ANTIGEN_LOG="${ADOTDIR}/antigen.log"

builtin . /usr/share/io.elementary.terminal/enable-zsh-completion-notifications || builtin true

# Using Antigen 2.0.x (from develop branch), it automatically check for cache and load it if its exists
typeset -A ANTIGEN_CHECK_FILES=("${HOME}/.zshrc" "${HOME}/.antigenrc")
source "${HOME}/.antigen.zsh"
antigen init "${HOME}/.antigenrc"

# OMZ settings
DEFAULT_USER=$USER
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="false"

POWERLEVEL9K_MODE=

HIST_STAMPS="dd.mm.yyyy"
HIST_IGNORE_SPACE="true"

ZSH_AUTOSUGGEST_USE_ASYNC=1

autoload -U bashcompinit
bashcompinit

source "$HOME/.shell/.keys"
source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.external"
source "$HOME/.shell/.p10k.v2.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
